/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Logocanvas.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Logocanvas.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.8, 0]} rotation={[Math.PI / 2, 0, 0]} scale={8.065}>
        <mesh geometry={nodes.Curve_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Curve_2.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Logocanvas.glb')
